name: ko-sales-rep-app
region: nyc
services:
- name: ko-sales-reps2
  environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: MMTNM/ko-sales-reps
  source_dir: /
  build_command: npm run build
  run_command: npm start
  http_port: 8080
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-1gb
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"
